service: google-calendar-slack-notifications
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2

functions:
  cronHandler:
    handler: index.run
    events:
      # Invoke Lambda function every hour from Mon-Fri
      # 1 minute passed the hour to catch the start of the next one
      - schedule: cron(1 * * * MON-FRI *)
